events {}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;

    server {
        listen 80;
        server_name patty-server.ddns.net;

        return 301 https://patrick-barclay.de$request_uri;
    }

    server {
        listen 443 ssl;
        server_name patty-server.ddns.net;

        return 301 https://patrick-barclay.de$request_uri;
    }

    server {
        listen 80;
        server_name patrick-barclay.de www.patrick-barclay.de;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name patrick-barclay.de www.patrick-barclay.de;

        ssl_certificate /etc/nginx/ssl/fullchain.pem;
        ssl_certificate_key /etc/nginx/ssl/_.patrick-barclay.de_private_key.key;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}