name: Deploy blog

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY_DEPLOYMENT }}
          port: ${{ secrets.PORT }}
          script: |
            cd /opt/photoblog
            git fetch origin main
            git reset --hard origin/main
            docker compose --profile prod up -d --build

